version: 2

sources:
  - name: warehouse
    schema: dbo

    tables:
      - name: Date
      - name: Time
      - name: Geography
      - name: Medallion
      - name: HackneyLicense
      - name: Trip
      - name: Weather